version: '3.8'

services:
  cloudformation:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: ./cloudformation
      dockerfile: Dockerfile
      args:
        - DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}
        - USER_NAME=${USER_NAME}
    volumes:
      - home:/home
    user: ${USER_NAME}
    stdin_open: true
    tty: true

volumes:
  home:
    name: ${VOLUME_NAME}

networks:
  default:
    name: ${NETWORK_NAME}
