version: '3.8'
services:
  cloudformation:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_NAME=${USER_NAME}
    volumes:
      - /etc/passwd:/etc/passwd:ro # Valid only if the host OS is Linux
      - /etc/group:/etc/group:ro # Valid only if the host OS is Linux
      - home:/home
    ports:
      - ${IP}:22:22
    stdin_open: true
    tty: true
volumes:
  home:
    name: ${VOLUME_NAME}
networks:
  default:
    name: ${NETWORK_NAME}