version: "3.8"
services:
  cloudformation:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_NAME=${USER_NAME}
    volumes:
      - /etc/passwd:/etc/passwd:ro # Valid only if the host OS is Linux
      - /etc/group:/etc/group:ro # Valid only if the host OS is Linux
      - home:/home
    command: >
      /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - ${IP}:22:22
volumes:
  home:
    name: ${VOLUME_NAME}